modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
license = "${license}"

[[mods]]
modId = "mctb"
version = "${version}"
displayName = "${mod_name}"
logoFile="mctb.png"
credits = "${credits}"
authors='''
P3NG00 = Original creator of the mod for Fabric
852Duarte = Ported for Forge
'''

description='''
A simple mod that adds more variables to the Crafting Table according to every type of wood in Minecraft!

This mod is a port from the original one maded for Fabric called "Oh, How the Crafting Has Tabled!"
https://www.curseforge.com/minecraft/mc-mods/oh-how-the-crafting-has-tabled
'''

[[dependencies.mctb]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.mctb]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"