modLoader="javafml" #mandatory

loaderVersion="[34,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

[[mods]] #mandatory

modId="mctb" #mandatory

version="1.16.4 - 1.0.0 " #mandatory

displayName="More Crafting Tables Mod" #mandatory

logoFile="mctb.png" #optional

authors='''
P3NG00 = Original creator of the mod for Fabric
852Duarte = Ported for Forge
'''

description='''
A simple mod that adds more variables to the Crafting Table according to every type of wood in Minecraft!

This mod is a port from the original one maded for Fabric called "Oh, How the Crafting Has Tabled!"
https://www.curseforge.com/minecraft/mc-mods/oh-how-the-crafting-has-tabled

'''

[[dependencies.mctb]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[34,)" #mandatory
ordering="AFTER"
side="BOTH"
